### ISSUE TITLE
Sometimes, apps that aren't themed aren't masked either, even though they should be.

### ISSUE THREAD

**Issue by cj81499** [AnemoneTeam/Anemone#156]
![slack for ios upload](https://cloud.githubusercontent.com/assets/9152032/18205986/db899618-70f2-11e6-92a0-a6ebb8d037e1.jpg)

**Comment by cj81499** [comment]
I think this is a mask cache issue. It seems like the mask cache isn't always cleared, or maybe it's cleared improperly.

**Comment by ravenleighii** [comment]
I'm thinking that this might be relavent to this post, so I'll add here instead of starting a new one. Basically I'll just post what I did in Slack. 
![slack for ios upload 1](https://cloud.githubusercontent.com/assets/16074998/18965118/b14335be-8630-11e6-8332-4481a2de24ab.png) Anemone is displaying the mask fine inside the app, but once applied, is not showing on springboard. 
![slack for ios upload](https://cloud.githubusercontent.com/assets/16074998/18965141/c8be67d6-8630-11e6-991e-87bcc9148634.png)

**Comment by ravenleighii** [comment]
That example I used was from Allegro theme, and he has placed quite a few masks in com.apple.mobileicons.framework which is why I chose it for this. 
![mask](https://cloud.githubusercontent.com/assets/16074998/18965404/f3a3e7e0-8631-11e6-8ee1-fa2f1ba8de1a.png)

**Comment by ravenleighii** [comment]
![img_0192](https://cloud.githubusercontent.com/assets/16074998/18965946/21c5e36a-8634-11e6-9c74-a9cf5ec6753b.jpeg) This is from the Anemone theme example, mask isn't working properly and it's also not covering un-themed icons (as cj81499  mentioned)

**Comment by coolstar** [comment]
@ravenleighii can you try the CircleIcons theme from https://coolstar.org/publicrepo and see if the mask from that theme works correctly?

**Comment by ravenleighii** [comment]
![img_0193](https://cloud.githubusercontent.com/assets/16074998/18967701/105e3bd4-863b-11e6-8d96-f0dfc8974de8.jpeg)

HEY, I'll have to see what you did, whatever it was, seems to work.

**Comment by ravenleighii** [comment]
tested on the Allegro theme effect, worked perfectly that time. Thank you Coolstar :)

**Comment by cj81499** [comment]
@coolstar Why would your mask work differently?

**Comment by coolstar** [comment]
Just got the issue with unthemed icons not masking. @cj81499 did you take your screenshot just after rebooting and re-jailbreaking with Pangu? Because that's when the issue happened here...

(Tapping Apply in Anemone fixed it)

**Comment by cj81499** [comment]
I'm still on 9.1, so I don't have the Pangu app. It seems to happen a lot when I unapply a theme.

**Comment by coolstar** [comment]
Weird, 9.1 should not have any issues like this. This is a known issue on 9.3.3, though due to the hybrid nature of icon masks. Icon Masks qualify as either part of IconBundles or Bundles depending on whether the icon it's masking is themed by an IconBundles theme...

it should be themed, but it does seem the Bundles component isn't working correctly (and I really should find something better to replace that part)

**Comment by cj81499** [comment]
Alright. I hope you can track down the issue. I've found that restarting seems to fix it for me most of the time if that helps you at all.
