### ISSUE TITLE
Add feature to support old Winterboard Info.plists and then convert to Anemone format.

### ISSUE THREAD

**Issue by tetra-fox** [AnemoneTeam/Anemone#16]

**Comment by cj81499** [comment]
Good idea! Seems like it would be relatively simple to throw together.

**Comment by coolstar** [comment]
The keyword here is "seems". It seems like something that would be easy but there's many quirks that will come into play. First off, it's not a simple conversion as there's different rendering quirks in the old WinterBoard plist. Second, CSS is way more complicated and WinterBoard doesn't even parse it, WinterBoard put webkit (basically safari) in the calendar icon to render it. We do not want to load WebKit into SpringBoard as it will cause a major performance degradation.

Second, regarding the quirks, the positioning won't be exactly correct. When I converted a few plists myself before themes started supporting Anemone, the margins are off as CSS puts actual margins while Anemone simply shifts the X and Y coordinates.

Overall, Anemone's text renderer is a lot simpler without so many advanced calculations in order to optimize for speed with the same rendered outcome in the end.

**Comment by cj81499** [comment]
Could you create a program that would allow you to input a winterboard info.plist and spit out a version for Anemone that uses the same numbers? Even if it's not exact, it would be easier than manually converting.

**Comment by coolstar** [comment]
@cj81499 unfortunately not due to the inconsistency of winterboard info.plist's

**Comment by cj81499** [comment]
Can you elaborate on this more, couldn't you just search for a value and then take what's after it and input that into an anemone plist? For example, search for "opacity: " and then take whatever comes after it until you reach ; and put it into the correct Anemome plist field?

**Comment by coolstar** [comment]
@cj81499 until you realize there's multiple ways to set opacity. e.g. rgba colors

**Comment by cj81499** [comment]
Yeah, but those color strings would also work in Anemone, no?

Maybe opacity was a bad example because there are multiple ways to achieve the opaque effect, but regardless of how it's done, the effect would still work with Anemone's methods.
