### ISSUE TITLE
Tweak conflict with Activator :(

### ISSUE THREAD

**Issue by kr0n1k** [AnemoneTeam/Anemone#212]
When I am using Anemone it works perfectly and no issues. However when I install Activator I get reboots and my screen freezes up to where I need to hard reset. It only happens when I have Activator and Anemone installed at the same time.

**Comment by gmawji** [comment]
But how do you know Anemone is the issue? Do you have anything to show it's Anemone and not Activator?

**Comment by kr0n1k** [comment]
Well I removed everything except the essentials like substrate and such installed Anemone and used my theme everything works fine. I install Activator and my phone starts to freeze and reboot most times after unlocking the device. When I remove Anemone my phone works fine. No issues with Activator but when I install Anemone then the issues start again and my phone starts rebooting. So it's a conflict between the tweaks because separately they work just fine on my iPhone but when I install them both my phone acts up. 

So I removed Anemone and went to winterboard and my phone is running perfectly fine.

If I uninstall Activator I can install Anemone with no problem and QuickDo will work with it. However Activator support is becoming a necessity for some tweaks and so I'm using winterboard and Activator as of now. I'm not the only person to have this issue. 

https://www.reddit.com/r/jailbreak/comments/5y2ld7/discussion_activator_puts_device_in_boot_loop/

https://www.reddit.com/r/jailbreak/comments/5xwete/question_updated_anemone_and_everytime_i_tried_to/

**Comment by KoHRdH** [comment]
My device stucks at respring. 
I only can use both tweaks when i disable the IconEffects Dylib. :(

**Comment by KoHRdH** [comment]
Is there no way to make it work? :(

**Comment by kr0n1k** [comment]
I'm not really sure to be honest. I had to remove Anemone and go with Winterboard for the time being. I couldn't stand having an unstable phone while at work. Weird because I don't have any issues at all with winterboard installed but if I switch to Anemone my phone starts rebooting and freezing up.

**Comment by KoHRdH** [comment]
It's weird because without AnemoneEffects everything works fine. Hope coolstar can help us. I dont want use WB or QuickDo as an alternative.

**Comment by jsteckler1** [comment]
So, this has been going on for a while now and well before I ever installed my current appswitcher (3D Switcher).

Basically, multiple times throughout the day my phone will become seemingly unresponsive. Generally, this seems to occur after I double tap the home button to switch apps, but it has also occurred after merely trying to return to my springboard.

I say seemingly because if I realize that the problem has arisen quickly enough, I'm able to force a respring from the app switcher. In that sense, it's not totally unresponsive (yet, at least). If not, I'm unable to do anything but lock the screen, in which case the screen will remain black until I perform a hard reset. Also, CrashReporter is turning up nothing. Unfortunately I can't seem to recreate the bug consistently enough to discern what the source of the issue might be myself.

Has anyone else run into this?

I've included my tweak list and I'm open to any and all suggestions.

Really appreciate any help I can get, because I can pretty much bank on 2 or 3 freezes per day minimum and it's getting incredibly tiresome.

Tweak List: 3DSwitcher 2 (iOS 9 & 10): 2.0.4 7-zip (POSIX): 4.57-3p Activator: 1.9.12 AlphaPaper: 1.1 Anchor: 2.0.4 Anemone: 2.1.1-27 App Admin: 1.0r-71 App Installer: 0.3-asu-1 AppDrawer: 1.4 AppList: 1.5.13 AppSync Unified: 6.0~b1 APT 0.6 Transitional: 1:0-23 APT 0.7 (apt-key): 0.7.25.3-3 APT 0.7 Strict (lib): 0.7.25.3-14 APT 0.7 Strict: 0.7.25.3-8 Base Structure: 1-4 Berkeley DB: 4.6.21-5 betterFiveIconDock: 1.0.4 BetterTextSelection: 1.1 BigBoss Icon Set: 1.0 BioProtect: 2.1-295 Bourne-Again SHell: 4.0.44-16 Boxy3(beta): 3.1b-66+debug bzip2: 1.0.5-8 Camera Tools: 1.4 CCSelector: 0.0.3 Cephei: 1.10 Cheader: 0.1.0-6+debug CleanNotifications10: 1.0.1-1 ColorBanners 2 (iOS 10): 1.0.2 ColorFlow 3 (iOS 10): 1.0.2 ColorMeBaddge: 1.0.6 Core Utilities (/bin): 8.12-9 Core Utilities: 8.12-13 CrashReporter: 1.15.0-1 Cydia Installer: 1.1.30 Cydia Substrate: 0.9.6301 Cydia Translations: 1.1.12 Darwin Tools: 1-5 Debian Packager: 1.18.10-12 Debian Utilities: 3.3.3ubuntu1-1p DetailedBatteryUsage: 1.1.1 Diff Utilities: 2.8.1-6 diskdev-cmds: 421.7-4 Eclipse 4 (iOS 10): 4.0.4 Espiro: 1.1 EW.WdgtPack.8: 1.0 EW3.iWidget_noWeather: 1.0 file-cmds: 220.7-3 Filza File Manager: 3.3.2 Find Utilities: 4.2.33-7 Flame: 1.3 Flex 3: 3~EarlyAccess3 FlipControlCenter: 1.0.4 Flipswitch: 1.0.15 FrontCamUnMirror: 2.2 GeniusHelper: 0.0.9 GIFViewer: 1.0.3-2 GNU Privacy Guard: 1.4.8-4 Gorgone: 0.0.1-5 GrandLS LockHTML: 1.0 grep: 2.5.4-3 gzip: 1.6-7 HideMeX (iOS 10): 1.0.6 HotDog: 3.3.3-1085+debug iCleaner: 7.6.0 IconSupport: 1.10.0.2-1 iFile: 2.2.0-1 InfoStats: 1.1.6 insanelyi Setup: 1.5-22 Instagram ++: 1.7r-162 InstaLauncher: 1.5.3 iOS Firmware: 10.2 iPhone Firmware (/sbin): 0-1 iWidgets: 1.3.2 KarenLocalizer: 1.0 KarenPrefs: 1.0.1 libbulletin: 0.1-80 libcolorpicker: 1.6-1 libcrashreport: 1.1.0-1 libpackageinfo: 1.1.0.1-1 libstatusbar: 1:0.9.9.0-1 libsymbolicate: 1.9.0-1 Link Identity Editor: 1:1.2.1 Lithium Ion: 1.3 LockGlyphX (iOS 10): 1.0.0 LockHTML4: 1.3~beta1-1 LockScreenGestureCleanUp: 0.5-1 LS Barebones - Tiny Mod: 1.6 LS Barebones Nano: 1.0 LS Barebones: 1.9 LZMA Utils: 4.32.7-5 MakeRespringsGreatAgain: 1.4 mikoto: 3.0.8 Moveable9: 1.0.0~beta29-6 New Curses: 5.7-15 Noctis (iOS 10): 1.9.2.1-1 NoSub (PalBreak w/ options): 1.3 NotiTinter: 1.0.1-2 onion: 0.0.2 OutOfControl: 6.1a Palert: 1.1.0-2 PAM (Apple): 32.1-4 PAM Modules: 36.1-5 Patcyh: 1.2.0 Phantom (Lite) for Snapchat: 5.3.3 pincrush: 0.9.2-1 PINN iOS9: 1.1 Polus Extra Apps Glyph Pack: 1.0 Polus: 2.2.1 Power Tap: 1.1.3-3 PreferenceLoader: 2.2.4~alpha1 Priority Hub 10: 2.2 Profile Directory: 0-2 QuickPowerMode: 1.0.1 readline: 6.0-8 Repo Icons: 1.0 RocketBootstrap: 1.0.5 sed: 4.1.5-8 shell-cmds: 118-7 Slushi: 1.0 Snapper 2: 1.2.6 Speedy: 1.0.0 Style HD for iOS 7, 8, 9: 1.5a Substrate Safe Mode: 0.9.6001 Surge: 0.20-1 Swipe Home: 2.3 system-cmds: 433.8-14 Tape Archive: 1.29-10 TechSupport Framework: 1.5.0.1-1 Tinc: 0.0.2-4+debug TranslucentMessages: 1.0.2 Twitter ++: 1.2r-44 TypeStatus 2 (iOS 7 – 10): 2.2.1 uasharedtools: 2.1r-61 UAUnbox: 0.0.2-1 UIKit Tools: 1.1.12 unrar: 3.6.8-2p unzip: 5.52-5p Vinilo: 1.0 Wethr: 1.1-1 Wifi Passwords List: 1.0.1-1 zip: 2.32-5p

**Comment by kr0n1k** [comment]
I

**Comment by kr0n1k** [comment]
Seems that disabling the z_AnemoneIconEffects.dylib has stopped the crashes and freezing.

**Comment by KoHRdH** [comment]
Yeah. Really weird. :(

**Comment by KoHRdH** [comment]
So what to do now? I've tried a lot. Nothing works. Winterboard is not a choice also QuickDo isnt a choice.

**Comment by coolstar** [comment]
It doesn't sound like there's a conflict between Anemone and Activator. It rather sounds like there's a serious issue with substrate, yalu102 or iOS 10.2.

Running Anemone and Activator on my iOS 9.3.3 device has no issues. I have seen the device kernel panic from just running AnemoneIconEffects, which does nothing more than use Apple's public image manipulation APIs to render overlays and underlays on icons. I'll have to run some tests and see if I can get the crash without substrate, and possibly even on a jailed device to see if it's an issue with substrate or yalu102

**Comment by kr0n1k** [comment]
Hopefully you can figure it out. Thanks for looking into it.

**Comment by coolstar** [comment]
Confirmed problem with yalu102. We unfortunately have to wait until either yalu102 is fixed or for Pangu to drop something :(

**Comment by coolstar** [comment]
https://github.com/kpwn/yalu102/issues/478
