### ISSUE TITLE
Curago (iOS Blocks) themed block icons cut into square

### ISSUE THREAD

**Issue by Aransh** [AnemoneTeam/Anemone#226]
iPhone 7 Plus, iOS 10.1.1.
It only happens with apps that have a themed icon, apps without a themed icon appear correctly with blocks.
For example, the music icon in my themes is: http://imgur.com/ODe6Wtk
When I open its block it looks like this:
http://imgur.com/UIyvmGW
I asked Andy and he said it's an Anemone bug and not Curago

**Comment by coolstar** [comment]
Issue with 3rd party tweak.

**Comment by cj81499** [comment]
@Aransh:

@coolstar's explanation is pretty brief. Try disabling everything except Anemone and Curago with iCleaner Pro to see if this still happens. If it does, one of the two devs are wrong.

Otherwise, re-enable tweaks until it happens again. Once it happens, you know the cause of the problem must be one of the tweaks you have enabled, so report the bug to the dev of the last tweak you enabled.
