### ISSUE TITLE
Add pngcrush for Theme Creators

### ISSUE THREAD

**Issue by meteochu** [AnemoneTeam/Anemone#43]
Winterboard allows theme creators to run pngcrush on the entire /Library/Themes folder and directly replacing the PNG files with a compressed version of it. Would be great if Anemone supported it too.

Reference: Winterboard Settings → Advanced → Optimize Themes

**Comment by cj81499** [comment]
Is this something that can be manually done through terminal or something?

**Comment by coolstar** [comment]
Anemone 1.1-138 adds Optitheme, which optimizes themes into an internal structure that Anemone can quickly load rather than perusing through all of /Library/Themes every time it needs an image. One of these optimization steps is running pincrush automatically. Hence, such a button is no longer necessary.
